const setupUnitApis = (http, BASE_URL) => ({
	getUnitList: ({ current, size, name, principalUserName, parentId }) =>
		http.get(`${BASE_URL}/api-user/group/pageList`, { current, size, name, principalUserName, parentId }),
	createUnit: ({
		name,
		parentId,
		typeCode,
		address,
		addressLat,
		addressLon,
		employeeNum,
		floorSpace,
		principalUserName,
		loginName,
		mobile,
		effectPicPath,
		designPicPath,
	}) =>
		http.post(`${BASE_URL}/api-user/group/insert`, {
			name,
			parentId,
			typeCode,
			address,
			addressLat,
			addressLon,
			employeeNum,
			floorSpace,
			principalUserName,
			loginName,
			mobile,
			effectPicPath,
			designPicPath,
		}),
	updateUnit: ({
		id,
		name,
		parentId,
		typeCode,
		address,
		addressLat,
		addressLon,
		employeeNum,
		floorSpace,
		principalUserName,
		mobile,
		effectPicPath,
		designPicPath,
	}) =>
		http.post(`${BASE_URL}/api-user/group/update`, {
			id,
			name,
			parentId,
			typeCode,
			address,
			addressLat,
			addressLon,
			employeeNum,
			floorSpace,
			principalUserName,
			mobile,
			effectPicPath,
			designPicPath,
		}),
	disableByUserId: userId => http.get(`${BASE_URL}/api-user/auth/disable`, { userId }),
	enableByUserId: userId => http.get(`${BASE_URL}/api-user/auth/enable`, { userId }),
	getUnitDetailById: id => http.get(`${BASE_URL}/api-user/group/detail/${id}`, {}),
	getGroupTree: () => http.get(`${BASE_URL}/api-user/group/tree`, {}),
	resetPassword: form => http.formPut(`${BASE_URL}/api-user/auth/resetPassword`, form),
	deleteGroupById: id => http.delete(`${BASE_URL}/api-user/group/delete/${id}`),
})

export default setupUnitApis
